version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: clone-against-humanity-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clone-against-humanity
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clone-against-humanity-api
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=clone-against-humanity

volumes:
  postgres_data:
