-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "rounds" DROP NOT NULL,
ALTER COLUMN "rounds" SET DEFAULT 10,
ALTER COLUMN "currentRound" DROP NOT NULL,
ALTER COLUMN "maxPlayers" DROP NOT NULL,
ALTER COLUMN "maxPlayers" SET DEFAULT 8,
ALTER COLUMN "started" DROP NOT NULL;
