name: Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER }}:latest --no-cache .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER }}:latest

      - name: Debug Print SSH Key
        run: echo "${{ secrets.SERVER_KEY }}"

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # Stop and remove old containers
            docker stop ${{ secrets.DOCKER_CONTAINER }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER }} || true
            docker stop ${{ secrets.DOCKER_DATABASE }} || true
            docker rm ${{ secrets.DOCKER_DATABASE }} || true

            # Remove existing images
            docker image prune -a -f

            # Start Postgres container
            docker run -d --name ${{ secrets.DOCKER_DATABASE }} --restart unless-stopped \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=clone-against-humanity \
            -p 5432:5432 \
            postgres:latest

            # Pull and start the API container
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER }}:latest
            docker run -d --name ${{ secrets.DOCKER_CONTAINER }} --restart unless-stopped \
            --link ${{ secrets.DOCKER_DATABASE }}:db \
            -p 443:4000 \
            -e NODE_ENV=production \
            -v /etc/letsencrypt:/etc/letsencrypt \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER }}:latest
