name: Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t clone-api .
          docker tag clone-api:latest ${{ secrets.DOCKER_USERNAME }}/clone-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/clone-api:latest

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker container prune -f
            docker image prune -a -f
            docker pull ${{ secrets.DOCKER_USERNAME }}/clone-api:latest
            docker stop clone-api || true
            docker rm clone-api || true
            docker run -d --name clone-api -p 80:4000 ${{ secrets.DOCKER_USERNAME }}/clone-api:latest
